# Base Configuration
baseurl = "/"
languageCode = "de-ch"
languageLang = "de"
title = "barvermieten - Catering Zürich - mobile Bar mieten in Zürich"
enableRobotsTXT = "true"
sectionPagesMenu = "main"

# Archetypes Management
MetaDataFormat = "yaml"

# taxonomies
[taxonomies]
#     tag = "tags"
#     category = "categories"
#     author = "authors"

[outputs]
  section = ["HTML", "JSON"]
